language: ruby
rvm:
  - 2.7.0
  - 2.6.3
  - 2.3.0
  - 2.2.2

jobs:
  # Use `fast_finish`, don't wait for any allowed failures.
  fast_finish: true

  include:
    - name: rb-2.2.2
      rvm: 2.2.2
      dist: trusty

  allow_failures:
    - name: rb-2.2.2
